### ISSUE TITLE
Plugin Disappears in Blender 3.2 on Mac

### ISSUE THREAD

**Issue by ecophobic** [EatTheFuture/camera_shakify#10]
Plugin installs and runs fine at first, then if you close the program and reopen, the plugin goes missing, and cannot be found in the menu, nor shows up after a reinstall, in either the info section or plugin viewer settings.

**Comment by cessen** [comment]
Thanks for the report!

I'm not able to reproduce this on my system, but my system isn't Apple so maybe there's something funky going on with that?

A couple of questions:
1. Are there any more details you can provide?  As it is, I really have no idea what might be causing this or how to investigate it.  The more details you can provide (e.g. launching Blender from the console and copy/pasting any output from there), the more likely it is that I can track this down and fix it.
2. Have you tried going through the same steps with installing other Blender addons?  I'm not aware of anything funky or special about Camera Shakify compared to other addons, so I'm wondering if this is just a general issue with installing Blender addons on your system.  (It still could be Camera Shakify, of course, but I just want to make sure, so don't sink a bunch of time into trying to track down an issue that doesn't actually exist.)

**Comment by cessen** [comment]
Closing due to lack of response from the reporter.  If anyone else runs into this issue and can provide any additional information, please feel free to re-open.
