### ISSUE TITLE
Shakify not Rendering on Sheepit

### ISSUE THREAD

**Issue by Fender-Blender** [EatTheFuture/camera_shakify#15]
I'm trying to render a found footage scene that I used shakify for on sheepit. The manual camera movement is showing but not the shakify addon. I tried baking, I chose the blender 2.93 option, nothing works. Help.

**Comment by cessen** [comment]
Yeah, Shakify shakes only work with the addon enabled, and it's probably not enabled on a third party render farm.  So you will need to bake it.

How are you trying to do the baking?  I outlined steps that work in [another issue](https://github.com/EatTheFuture/camera_shakify/issues/5#issuecomment-1027308250).

**Comment by cessen** [comment]
Closing due to lack of response from submitter.  If anyone else has problems with baking, feel free to respond to this issue or open a new one.

**Comment by guus6457** [comment]
when i bake it dont work
