### ISSUE TITLE
Addon not working in Blender 3.5 on MacOS

### ISSUE THREAD

**Issue by lndfebfdjo** [EatTheFuture/camera_shakify#18]
Blender Version 3.5.1

I used the 3.4 workaround (the one where you change lines `209` and `210`), the addon installed but when I add shake in the menu, the camera does nothing. I've tried this on stationary cameras, cameras parented to an empty, cameras following a curve and animated with keyframes, still nothing.

Steps to reproduce:
1. Change lines `209` and `210` to install properly
2. Install
3. Add shake to a camera.
4. Nothing happens

I'm guessing that the workaround is the issue, maybe it is different in 3.5 than in 3.4

**Comment by cessen** [comment]
> I used the 3.4 workaround (the one where you change lines 209 and 210)

I'm not entirely sure I know what you're talking about.  It sounds similar to issue #6 (which involves those lines), but that was already fixed.

Have you downloaded the [latest version of the addon](https://github.com/EatTheFuture/camera_shakify/archive/refs/heads/master.zip)?

**Comment by lndfebfdjo** [comment]
Sorry for lack of response, but it works now. Thank you very much!
