### ISSUE TITLE
Request: keyframe type of shake?

### ISSUE THREAD

**Issue by Sarah-C** [EatTheFuture/camera_shakify#20]
I have a scene where the camera's "standing still", and then runs to a new place....  I'd love to be able to switch between "Investigate", and "HandyCam Run".

**Comment by cessen** [comment]
You can do this by adding more than one camera shake, and animating their respective influences.  That also allows you to smoothly blend between the different shakes, whereas key framing which shake is active directly would result in a sharp jump.
