### ISSUE TITLE
Some objects disappear for a frew frames with this addon enabled

### ISSUE THREAD

**Issue by chickenborn** [EatTheFuture/camera_shakify#21]
**Blender Version**
Blender 3.6.5

**Describe the bug**
When the script is enabled, some objects are not rendered for every frame.
In my scene for examples, the eyes, hairs and some cloth disappear for a few frames.
It is consistent. When I render through viewport the objects are shown for more frames than when I render through eevee.

**To Reproduce**
So far I encountered this issue only with a linked blend file.

**Comment by cessen** [comment]
Thanks for the issue report!  Can you provide a blend file that demonstrates the issue?

**Comment by cessen** [comment]
Closing due to lack of response from the reporter.  If anyone else runs into this, feel free to open another issue.  But please provide repro steps so I can track it down and fix it.
