### ISSUE TITLE
Doesn't work on Blender v4.0

### ISSUE THREAD

**Issue by basicusername123** [EatTheFuture/camera_shakify#24]
Blender 4.0
My version of Blender simply can't run Camera Shakify.
Today i tried using this and all of a sudden it would not appear. I need to know why.
To put it short, It won't appear.

To reproduce, just install and try to run on v4.0

Expected: Run perfectly

**Comment by cessen** [comment]
I'm unable to reproduce the issue.  Freshly downloading the camera shakify addon and installing it on Blender 4.0 is working fine for me.

Can you provide any more details of exactly the steps you're taking that result in this?  And can you launch Blender from the console and paste what it outputs here?

**Comment by damankarora** [comment]
Getting the following error on running on Blender 4.1
<img width="1440" alt="Screenshot 2024-04-09 at 1 37 07 AM" src="https://github.com/EatTheFuture/camera_shakify/assets/44134180/ffe0454d-3910-4a7f-b7f9-9a30629796ff">

Workaround that I did: 
in __init__.py, L.No: 209, 210 
I cast the float value into a string. 

Can you tell me how it can impact the functionality of the addon effect?

`    constraint.frame_start = int(action_range[0])
    constraint.frame_end = int(action_range[1])
`

**Comment by damankarora** [comment]
> Getting the following error on running on Blender 4.1 <img alt="Screenshot 2024-04-09 at 1 37 07 AM" width="1440" src="https://private-user-images.githubusercontent.com/44134180/320638315-ffe0454d-3910-4a7f-b7f9-9a30629796ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDgzNzcsIm5iZiI6MTcxMjYwODA3NywicGF0aCI6Ii80NDEzNDE4MC8zMjA2MzgzMTUtZmZlMDQ1NGQtMzkxMC00YTdmLWI3ZjktOWEzMDYyOTc5NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIwMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjBjZDgxNDcxNGE2NWExM2VjZTEzYzRiZDg2NWY5M2JkODZiMWFmYTkwOTY1MjU1MGZiYTczZmIyNzJhNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ooLyPvLprY73xbbQ89jt6X51DhHpw1VG9bX9KQrSnRo">
> 
> Workaround that I did: in **init**.py, L.No: 209, 210 I cast the float value into a string.
> 
> Can you tell me how it can impact the functionality of the addon effect?
> 
> ` constraint.frame_start = int(action_range[0]) constraint.frame_end = int(action_range[1])`

@cessen

**Comment by cessen** [comment]
Are you sure you actually downloaded the latest CameraShakify?  Because the error you're getting looks identical to issue #8 which was fixed quite a while ago.

Other people have also filed the same issue, and it always turns out they were using an older version of CameraShakify.  I don't know where people are downloading these older versions from.  But to get the latest version, you should always be downloading from this github repository.

**Comment by cessen** [comment]
Closing due to this likely being an old bug that's already fixed, and a lack of response from the reporters to say otherwise.

**Comment by damankarora** [comment]
> Closing due to this likely being an old bug that's already fixed, and a lack of response from the reporters to say otherwise.

Can you please share PR of the fix you did? I feel i was on the latest version.  I downloaded the zip directly from this repo.

**Comment by cessen** [comment]
@damankarora In the error message in your screenshot, you can see that the version of Camera Shakify you have has the line:

```
constraint.frame_start = action_range[0]
```

However, if you look at the same part of the file in this repo those same lines are the following:

https://github.com/EatTheFuture/camera_shakify/blob/113f761615f18e1916f21a5702eba144fdce2b20/__init__.py#L210-L211

The floor and ceiling functions return `int`s, so that addresses this same issue.  The floor and ceil calls were added about two years ago in https://github.com/EatTheFuture/camera_shakify/commit/3088d52e1090bd71a5d04f110663204e372875b5.

**Comment by damankarora** [comment]
> @damankarora In the error message in your screenshot, you can see that the version of Camera Shakify you have has the line:
> 
> ```
> constraint.frame_start = action_range[0]
> ```
> 
> However, if you look at the same part of the file in this repo those same lines are the following:
> 
> https://github.com/EatTheFuture/camera_shakify/blob/113f761615f18e1916f21a5702eba144fdce2b20/__init__.py#L210-L211
> 
> The floor and ceiling functions return `int`s, so that addresses this same issue. The floor and ceil calls were added about two years ago in [3088d52](https://github.com/EatTheFuture/camera_shakify/commit/3088d52e1090bd71a5d04f110663204e372875b5).

In the latest file, it seems fine. Floor and ceil will return non floating numbers. I don’t clearly remember where my friend had downloaded your plugin from. Probably that source is not updated. Anyhow, thanks for clarifying and apologies for wasting your time.

**Comment by cessen** [comment]
No worries!  It happens.

> I don’t clearly remember where my friend had downloaded your plugin from. Probably that source is not updated.

If you can ask your friend where he got it, I would really like to know.  I get this same bug report repeatedly, and I would really like to find out where people are getting this outdated version so I can ask whoever it is to update the link to just point at this repo.
