### ISSUE TITLE
Potential corruption of any additional scene using linked collection with camera shakify.

### ISSUE THREAD

**Issue by loicbramoulle** [EatTheFuture/camera_shakify#31]
**Blender Version**
4.2

**Describe the bug**
I do a link duplicate of my main scene (cycles), to set it up to render fog with eevee. This scene systematically get corrupted and crashes blender if opened or right-clicked. After investigation I suspect it might be Shakify, as IGNORING this python script (in factory reset mode) does solve the corruption/ does not crash blender on opening the secondary scene inside the file.

**To Reproduce**
1. Have a second scene (linked duplicate) so that your shakified cameras are in both scenes.
2. close and re-open the file, go to this secondary scene
3. blender crashes (on my side at least.)

This is the script that causes the scene to be corrupt, letting it run will provoke the secondary scene to crash if opened, ignoring the script will cleanse the scene and it will open without crash:
![image](https://github.com/user-attachments/assets/59fc337b-1887-45d4-99d1-420d9318a8a7)
I might be wrong, but I just have a feeling this script comes from Shakify.

Another pointer is that it seems like a 4.2 factory reset will instantly crash if opening any file that uses Shakify, I might also be wrong as I might not have sampled enough files, but it seems like it.

I'be just tried on a blank file, and it does not seem to come from Shakify, but I don't see what else could run something like that, that seems to be a wiggle. (doesn't seem to be Wobbly Wiggler either.)

**Comment by loicbramoulle** [comment]
Ok the culprit is actually **Flare Wizzard.**
Sorry for any ping.

**Comment by cessen** [comment]
No worries!  Thanks for the report regardless.  :-)
