### ISSUE TITLE
Please submit to extensions.blender.org

### ISSUE THREAD

**Issue by slrgt** [EatTheFuture/camera_shakify#32]
This is a great addon and it would be great to now have it included in the default Blender extensions section. Please submit it to https://extensions.blender.org/ :)

**Comment by cessen** [comment]
Thanks for the suggestion!  That's a good idea, and it's in the plans.  Just haven't gotten around to it yet.  I'll leave this issue open until that's done.

**Comment by cessen** [comment]
Done!
https://extensions.blender.org/add-ons/camera-shakify/

**Comment by slrgt** [comment]
thanks!
