### ISSUE TITLE
Error adding shake item in Blender 3.2

### ISSUE THREAD

**Issue by naemlon** [EatTheFuture/camera_shakify#8]
**Blender Version**
3.2.0

**Describe the bug**
Python error adding Camera Shakify to a camera in Blender 3.2:

```
Python: Traceback (most recent call last):
  File "/home/naemlon/.config/blender/3.2/scripts/addons/camera_shakify-master/__init__.py", line 466, in execute
    rebuild_camera_shakes(camera, context)
  File "/home/naemlon/.config/blender/3.2/scripts/addons/camera_shakify-master/__init__.py", line 376, in rebuild_camera_shakes
    build_single_shake(camera, shake_item_index, collection, context)
  File "/home/naemlon/.config/blender/3.2/scripts/addons/camera_shakify-master/__init__.py", line 209, in build_single_shake
    constraint.frame_start = action_range[0]
TypeError: bpy_struct: item.attr = val: ActionConstraint.frame_start expected an int type, not float
```

**To Reproduce**
1. select camera, go to camera data in the outliner
2. Click on '+' (add shake item)
3. See error (shake item appears in list, but camera does not move)

**Expected behavior**
Working addon like in Blender 3.1

**Comment by cessen** [comment]
This appears to be the same error as issue #6, which has already been fixed.  Are you sure you've downloaded the latest version of the addon?

**Comment by naemlon** [comment]
Weird, I (thought I) was using 0.2.0 downloaded at the end of March while the last commit was on Feb 25. Now I downloaded the zip again, installed it and it works. Comparing both zips shows they are identical.
Perhaps I did not install the newer version and the installed version was from before the patch with the same version number.

Thank you!
